[package]
name = "privacy-pools-stwo"
version = "0.1.0"
edition = "2021"

[dependencies]
stwo-prover = { git = "https://github.com/piotr-stec/stwo-fork-keccak", branch = "feat/gnark" }
stwo-polynomial = { git = "https://github.com/piotr-stec/stwo-polynomial", branch = "feat/gnark" }
# stwo-polynomial = {path = "/home/piotrstec/dev/stwo-polynomial"}
# stwo-prover = {path = "/home/piotrstec/dev/stwo-fork-keccak/crates/prover"}
num-traits = "0.2"
thiserror = { version = "2.0.12", default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false }
serde.workspace = true
serde_json.workspace = true
alloy.workspace = true
tokio.workspace = true
itertools = "0.13"
hex = "0.4"

[dev-dependencies]
zkhash = { git = "https://github.com/AntoineFONDEUR/poseidon2.git", branch = "poseidon2-M31" }
eyre = "0.6"
rand = "0.8"

[[test]]
name = "e2e"
path = "e2e/mod.rs"
